// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvpaewutdxxkpxtokfkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2cGFld3V0ZHh4a3B4dG9rZmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDU5NjIsImV4cCI6MjA2ODA4MTk2Mn0.4N4YXu63XAnz5x5NyDGjIjkMZY0DE3XQeGNF31DyGEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});